baseURL = "http://www.chende.ren"
languageCode = "zh-CN"
title = "闪电侠的小黑板"
theme = "maupassant"

#googleAnalytics = "GA ID"       ## 分析统计
#googleAnalytics = ""            ## UA-XXXXXXXX-X
disablePathToLower = true       # 是否禁止URL Path转小写
summaryLength = 170             # 限制列表摘要字数
hasCJKLanguage = true           # 这一句必须在summaryLength后面
enableEmoji = true

# 打印信息，用于调试 {{ printf "%#v" . }}

[author]
    name = "闪电侠"
[params]
    author = "闪电侠"
    subtitle = "专注于C、Node.js、Golang、Dart、WEB开发框架、高性能高可用架构、团队管理"
    keywords = "闪电侠,C,Go,Golang,Node.js,Python,Ruby,Flutter,Dart,博客,部门管理,软件架构,Web框架,高可用,高性能"
    description = "专注于IT互联网，包括但不限于Go语言(golang)、C/C++、Flutter、Dart、Python、项目管理、软件架构等"

    localSearch = "true"            # 开启站内搜索
    beian = "京ICP备XXXX号-1"       # 备案号
    fancybox = "true"               # 图片点击放大
    busuanzi = true                 # 页面计数器
    summaryLen = 170                # 限制列表摘要字数
    mainSections = ["tech", "tools", "idea", "licai", "about"]
    rightSections = ["tech", "idea", "licai"]

    # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
    #customCSS = ['douban.css', 'other.css']
    # if ['custom.css'], load '/static/css/custom.css' file
    #customJS = ['douban.js']
    # if ['custom.js'], load '/static/js/custom.js' file

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[[params.links]]
    title = "闪电侠的小黑板"
    name = "闪电侠的小黑板"
    url = "http://www.chende.ren/"

[[params.links]]
    title = "飞雪无情的博客"
    name = "飞雪无情的博客"
    url = "http://www.flysnow.org"

#[[params.ads]]
#    title = "领取￥1888阿里云产品通用代金券"
#    url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=jdg9oj97"

# 插件
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[params.flowchartDiagrams]
    enable = true
    options = ""

[params.sequenceDiagrams]
    enable = true
    options = ""
    # default: "{theme: 'simple'}"

# 评论，disqus或utteranc
#disqusShortname = "yourdiscussshortname"   # 是否开启 disqus 评论，不要和utteranc同时开启
[params.utteranc]
    enable = true
    repo = "xxx/xxx"                        # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"                  # 表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light"                  # 样式主题，有github-light和github-dark两种

# 菜单
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[menu]
[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
[[menu.main]]
    identifier = "idea"
    name = "杂思"
    url = "/idea/"
    weight = 3
[[menu.main]]
    identifier = "licai"
    name = "理财"
    url = "/licai/"
    weight = 4
[[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 5
[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 6

# 代码高亮
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[markup]
[markup.highlight]
    #更多高亮样式：https://xyproto.github.io/splash/docs/all.html#emacs
    lineNos = true
    #style = "github"
    #style = "friendly"
    style = "perldoc"
    #style = "vs"
    #style = "tango"
    #style = "emacs"

    #style = "colorful"
    #style = "monokailight"
    #style = "paraiso-light"
    #style = "manni"

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 博客路径生成规则/年/月/日/Markdown文件的title或者filename加上.html结尾，注意路径都是小写
# 注意新版hugo(0.78以后吧) --uglyURLs 不再支持，取代的做法就是设置系统的环境变量:
# env HUGO_UGLYURLS="true" hugo server -D
# env HUGO_UGLYURLS="true" hugo -D
# 但是全站都变成.html结尾的路径了，并不好，可以单独在每份FrontMatter中指定url来设置
#uglyurls = false
#[frontmatter]
#    date = [":filename", ":default"]
#[permalinks]
#    #post = "/:year/:month/:day/:filename"
